services:
  postgres_pgvector:
    image: pgvector/pgvector:0.7.4-pg16
    restart: always

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: codely
      POSTGRES_PASSWORD: c0d3ly7v
    ports:
      - "5432:5432"
    volumes:
      - ./databases/postgres:/docker-entrypoint-initdb.d

  mariadb:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adminpassword
      MYSQL_DATABASE: mooc
      MYSQL_USER: codely
      MYSQL_PASSWORD: c0d3ly7v
      TZ: UTC
    ports:
      - "3306:3306"
    volumes:
      - ./databases/mysql:/docker-entrypoint-initdb.d
