services:
  postgres_pgai:
    image: timescale/timescaledb-ha:pg17-ts2.17
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: codely
      POSTGRES_PASSWORD: c0d3ly7v
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./databases:/docker-entrypoint-initdb.d

  pgai-vectorizer_worker:
    image: timescale/pgai-vectorizer-worker:v0.2.1
    restart: unless-stopped
    environment:
      PGAI_VECTORIZER_WORKER_DB_URL: postgres://codely:c0d3ly7v@postgres_pgai:5432/postgres
      OLLAMA_HOST: http://host.docker.internal:11434
    command: [ "--poll-interval", "5s" ]

volumes:
  db_data:
